<?php

//in this file, define 

$ms = //menu structure

new menin('','', 0, '', array(
//   new menin("$bp/actualite",'Actualité', 1, 'gibraltar3_740x85.jpg', array()),
   new menin("$bp/index",'Introduktion', 1, 'gibraltar3_740x85.jpg', array()),
   new menin("$bp/paedagogik",'Pædagogik', 1, 'rtg1_740x85.jpg', array()),
   new menin("$bp/praktisk_info",'Praktisk Info', 1, 'citrus_740x85.jpg', array()),

));
php?>


